### ISSUE TITLE
The apply button doesn't work

### ISSUE THREAD

**Issue by gabehowe** [GoldenDragons772/ftc772.org#3]
The apply button in the top right corner of every page doesn't do anything when clicked and the text is selectable.
![image](https://github.com/GoldenDragons772/ftc772.org/assets/31964173/f7f83e25-cda1-46a5-983b-e07e4901110c)

**Comment by gabehowe** [comment]
is it to apply to the school or apply to the team?

**Comment by OPstriker** [comment]
this should be fixed now...
